// @ts-check
import { defineConfig } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
// Sitemap is generated by the custom endpoint at src/pages/sitemap.xml.ts
// (single /sitemap.xml with hreflang alternates) instead of @astrojs/sitemap.
export default defineConfig({
  site: 'https://nutriswapper.com',
  vite: {
    plugins: [tailwindcss()]
  }
});